In [1]:
import numpy as np

In [17]:
a=np.array([])
b=np.array([1,2,3,4])
c=np.array([[1,2,3,6],[5,6,7,8],[4,5,6,7]])

In [18]:
a

array([], dtype=float64)

In [19]:
type (a)

numpy.ndarray

In [20]:
b

array([1, 2, 3, 4])

In [21]:
type(b)

numpy.ndarray

In [22]:
c

array([[1, 2, 3, 6],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [23]:
type (c)

numpy.ndarray

In [24]:
c.ndim

2

In [25]:
b.ndim

1

In [26]:
a.size

0

In [27]:
b.size

4

In [28]:
c.size


12

In [29]:
c.shape

(3, 4)

In [30]:
b.shape

(4,)

In [33]:
n=np.array([[2,3,4,5],[23,34,45,56],[123,234,345,456]])


In [34]:
n.shape

(3, 4)

In [2]:
n=np.array([[2,3,4,5],[23,34,45,56],[123,234,345,456]])


NameError: name 'np' is not defined

In [3]:
print(n)

NameError: name 'n' is not defined

In [4]:
import numpy as np

In [5]:
n=np.array([[2,3,4,5],[23,34,45,56],[123,234,345,456]])

In [6]:
n


array([[  2,   3,   4,   5],
       [ 23,  34,  45,  56],
       [123, 234, 345, 456]])

In [9]:
n[2,3]

456

In [10]:
n[1,1]

34

In [11]:
n[0,0]

2

In [15]:
n[2,1:4]

array([234, 345, 456])

In [17]:
n[1:4,2:4]

array([[ 45,  56],
       [345, 456]])

In [20]:
n[0:3,3]

array([  5,  56, 456])

In [21]:
n[1,:2]

array([23, 34])

In [22]:
n

array([[  2,   3,   4,   5],
       [ 23,  34,  45,  56],
       [123, 234, 345, 456]])

# ARRANGE

In [24]:
np.arange(2,34)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [25]:
np.arange(5.5,55.4)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5, 50.5, 51.5, 52.5, 53.5, 54.5])

# RESHAPE

In [38]:
a=np.arange(12).reshape(3,4)

In [39]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [41]:
np.sqrt(81)

9.0

In [42]:
a.max()


11

In [44]:
a.min()

0

In [45]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
n.argmin()

0

In [47]:
n.argmax()

11

In [48]:
a*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [49]:
a+12

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
np.random.rand(2,2)

array([[0.41777568, 0.12682758],
       [0.83901172, 0.42901535]])

In [51]:
np.random.rand(2)

array([0.71870483, 0.19454037])

In [53]:
np.random.randn(2,2)

array([[ 0.42668507, -0.51392904],
       [-0.77891109, -0.14110034]])

In [55]:
np.random.randint(2,99,9)

array([57, 35, 25, 66, 35, 42, 20, 70, 49])

In [59]:
np.random.randint(2,99,9).reshape(3,3)

array([[55, 32, 91],
       [82, 28, 53],
       [21, 90, 16]])

In [61]:
f

array([[22, 81, 23],
       [91, 80,  5],
       [86, 64, 74]])

In [63]:
f.sum()

526

In [64]:
f.sum(axis=1)

array([126, 176, 224])

In [65]:
f.sum(axis=0)

array([199, 225, 102])

# 3D

In [71]:
#Nan -not a number


In [72]:
x = np.array([12,23,np.nan,55,67,np.nan])

In [73]:
x

array([12., 23., nan, 55., 67., nan])

In [74]:
x.dtype

dtype('float64')